data-directory: /home/ddutt/work/suzieq/tests/data/multidc/parquet-out
service-directory: /home/ddutt/work/suzieq/config
schema-directory: /home/ddutt/work/suzieq/config/schema
temp-directory: /tmp/suzieq
# kafka-servers: localhost:9093
logging-level: WARNING
