<<<<<<< HEAD
---
=======
>>>>>>> 8f1b457c9d5614c7599ab52eac28533ac08218e0
apiVersion: v1
kind: ConfigMap
metadata:
  name: suzieq-inventory
  namespace: suzieq
data:
  eos.yml: |
    - namespace: eos
      hosts:
        - url: https://neteng:arista123@10.255.0.10 devtype=eos
  junos.yml: |
    - namespace: junos
      hosts:
        - url: ssh://neteng:juniper123@10.255.0.11 devtype=junos-mx
<<<<<<< HEAD
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: suzieq-config
  namespace: suzieq
data:
  suzieq-cfg.yml: |
    data-directory: /suzieq/parquet
    service-directory: /suzieq/config
    schema-directory: /suzieq/config/schema
    temp-directory: /tmp/
    # kafka-servers: localhost:9093
    logging-level: WARNING
    period: 15
    API_KEY: 496157e6e869ef7f3d6ecb24a6f6d847b224ee4f
    rest_certfile: /suzieq/tls/tls.crt
    rest_keyfile: /suzieq/tls/tls.key

=======
>>>>>>> 8f1b457c9d5614c7599ab52eac28533ac08218e0
