---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: suzieq
  name: parquet-volume
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/suzieq/parquet"